### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by wermaxta** [m0nad/HellRaiser#11]
Hi my OS is Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali2 (2018-01-11) x86_64 GNU/Linux
when i type    bundle exec rake db:migrate  i get this message
rake aborted!
NoMethodError: undefined method `new_with_config' for ActionDispatch::Routing::RouteSet:Class
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:533:in `routes'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:580:in `block in <class:Engine>'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:44:in `tsort_each_child'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:44:in `tsort_each_child'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:44:in `tsort_each_child'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:44:in `tsort_each_child'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
/root/stuff/HellRaiser/config/environment.rb:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:328:in `require'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:328:in `require_environment!'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:448:in `block in run_tasks_blocks'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/var/lib/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/var/lib/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

And when i start   foreman s i get this 
https://pastebin.com/r0S3KrgE
Thank you :)

**Comment by frank184** [comment]
@wermaxta this is very strange... 

Essentially your stack trace is saying that `new_with_config` a method used by the Rails internally for routing is undefined.

Can you confirm that other Rails applications are running normally using your build?

You should be able to do something along the lines of:

```
rails new test
cd test
rails s
```
And then go to localhost:3000 in any web browser.

Thanks!
